services:
  php:
    image: ghcr.io/bakez1029/php-fpm-nginx-lab/php-app:latest
    env_file:
      - ./src/.env
    networks:
      - appnet

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - appnet

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata_prod:/var/lib/mysql
    networks:
      - appnet

volumes:
  dbdata_prod:

networks:
  appnet:
